services:
  - type: web
    name: bulk-indexer
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
